version: "3"
services:
  myportfolio:
    container_name: myportfolio
    build: .
    restart: always
    env_file:
      - .env
    environment:
      - FLASK_ENV=development
    ports:
      - "5001:5000"
    volumes:
      - .:/myportfolio
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    container_name: mysql
    image: mariadb
    command: --max_allowed_packet=32M
    restart: always
    env_file:
      - .env
    volumes:
      - mydatabase:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-uroot", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 20s
      retries: 10

volumes:
  mydatabase:
