services:
  myportfolio:
    container_name: myportfolio
    build: .
    restart: always
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    container_name: mysql
    image: mariadb
    command: --max_allowed_packet=32M
    restart: always
    env_file:
      - .env
    volumes:
      - mydatabase:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-uroot", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 20s
      retries: 10

  nginx:
    container_name: nginx
    image: jonasal/nginx-certbot
    restart: always
    environment:
      - CERTBOT_EMAIL=leesamuel423@gmail.com
      - DOMAINS=leesamuel423.duckdns.org
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./user_conf.d:/etc/nginx/user_conf.d
      - certbot_www:/var/www/certbot
    depends_on:
      - myportfolio

volumes:
  mydatabase:
  nginx_secrets:
  certbot_www:
